[build]
  base    = "RetailIQ/retail-dashboard"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200